
# Site config
lang: en
encoding: utf-8
title: Tuvok
author: Commander Tuvok
email:
avatar: https://stt.wiki/w/images/4/4a/Maquis_Tuvok_Head.png
description: The logical Jekyll theme for an elegant GitHub Pages blog.
social:
  links:
    - # githuh
    - # twitter
    - # facebook
    - # linkedin
    - # google plus

# Jekyll config
markdown: kramdown
highlighter: rouge
excerpt_seperator: "<!--more-->"
paginate: 6 # number of posts per page

# Disqus config
disqus_shortname: true

# Google config
google_analytics:

# Mailchimp config
mailchimp_action: true
mailchimp_nobot: true

# Override template defaults
overrides:
  #date_format: "%b %-d, %Y"
  post_title_length: 30
  post_excerpt_length: 40
  words_per_minute: 200
  paginator_pages: 2 # max number of upper/lower links in the panginator

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Front matter defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: page
      disqus_comments: true
      read_time: true

exclude:
  - Gemfile
  - Gemfile.lock
